# fly.toml app configuration file generated for restless-fire-4347 on 2023-08-21T14:43:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-fire-4347"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
